### ISSUE TITLE
Leechflix could result in a account banned if used in TORRENTLEECH/IPTORRENTS?

### ISSUE THREAD

**Issue by ZeroCool22** [tsoernes/leechflix#1]
Juast asking...

**Comment by tsoernes** [comment]
Theoretically, yes, because the underlying torrent client is not on the allowed list. However, I've been using the underlying torrent client for over a year and haven't heard anything so I think it's ok. That said I'm not sure leechflix works anymore with regards to tracker login and scraping. You'll have to try.
